=== magza1/mzapp/code/Vnecoms/VendorsGroup/etc/advanced_group.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configDeclaration"/>

    <xs:complexType name="configDeclaration">
        <xs:sequence>
            <xs:element ref="advanced_group" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="advanced_group">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="group" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        
		<xs:unique name="uniqueGroupId">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all groups for each section
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="group"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:attributeGroup name="elementsAttributeGroup">
        <xs:attribute name="id" type="typeId" use="required" />
        <xs:attribute name="translate" type="xs:string" use="optional" />
        <xs:attribute name="type" type="xs:string" use="optional" />
        <xs:attribute name="sortOrder" type="xs:float" use="optional" />
    </xs:attributeGroup>

    <xs:element name="group">
        <xs:annotation>
            <xs:documentation>
                Group Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="label" type="xs:string" />
                    <xs:element name="fieldset_css" type="xs:string" />
                    <xs:element name="frontend_model" type="typeModel" />
                    <xs:element name="comment" type="xs:string" />
                    <xs:element ref="field" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="elementsAttributeGroup"/>
        </xs:complexType>

        <xs:unique name="uniqueFieldId">
            <xs:annotation>
                <xs:documentation>
                    Attribute id is unique under all fields for each group
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="field"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="field">
        <xs:annotation>
            <xs:documentation>
                Field Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="label" type="xs:string" />
                    <xs:element ref="comment" />
                    <xs:element name="required" type="xs:string" />
                    <xs:element name="frontend_class" type="xs:string" />
                    <xs:element name="frontend_model" type="typeModel" />
                    <xs:element name="backend_model" type="typeModel" />
                    <xs:element name="source_model" type="typeModel" />
                    <xs:element name="validate" type="xs:string" />
                </xs:choice>
            </xs:sequence>

            <xs:attributeGroup ref="elementsAttributeGroup"/>
        </xs:complexType>

        <xs:unique name="uniqueAttributeType">
            <xs:annotation>
                <xs:documentation>
                    Attribute type is unique under all node attributes per field
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath=".//attribute"/>
            <xs:field xpath="@type"/>
        </xs:unique>
    </xs:element>

    <xs:attributeGroup name="attributeAttributeGroup">
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:anyAttribute processContents="lax"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="commentAttributeGroup">
        <xs:attribute name="model" type="xs:string" use="optional" />
        <xs:anyAttribute processContents="lax"/>
    </xs:attributeGroup>



    <xs:simpleType name="typeId">
        <xs:annotation>
            <xs:documentation>
                Item id attribute for elements section, group, field can has only [a-zA-Z0-9/_]. Minimal length 2 symbol. Case sensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]{1,}" />
            <xs:minLength value="2" />
        </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="typeModel">
        <xs:annotation>
            <xs:documentation>
                Item model attribute can has only [a-zA-Z0-9_]. Minimal length 5 symbol. Case insensitive.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\\\\:]+" />
            <xs:minLength value="5" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="comment">
        <xs:annotation>
            <xs:documentation>
                Comment type
            </xs:documentation>
        </xs:annotation>

        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="1" processContents="lax" />
            </xs:sequence>
            <xs:attributeGroup ref="commentAttributeGroup"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== magza1/mzapp/code/Vnecoms/VendorsGroup/etc/advanced_group.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Vnecoms_VendorsGroup:etc/advanced_group.xsd">
<advanced_group>
	<group id="catalog" translate="label tooltip" type="text" sortOrder="10">
		<label>Catalog</label>
		<field id="can_add_product" translate="label" type="select" sortOrder="10">
			<label>Can Add New Product</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
			<comment>If this option is set to No, Sellers in this group can't add new products from seller panel. They can only edit assigned products.</comment>
		</field>
		<field id="product_limit" translate="label" type="text" sortOrder="20">
			<label>Product Limitation</label>
			<frontend_class>validate-number</frontend_class>
			<comment><![CDATA[Maximum number of products that you allow sellers in this group to add from seller panel.<br />Leave blank or zero to allow seller to add unlimited products.]]></comment>
		</field>
	</group>
	<group id="sales" translate="label tooltip" type="text" sortOrder="20">
		<label>Sales</label>
		<field id="can_cancel" translate="label" type="select" sortOrder="10">
			<label>Can Cancel Order</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
		</field>
		<field id="can_create_invoice" translate="label" type="select" sortOrder="20">
			<label>Can Create Invoice</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
		</field>
		<field id="can_create_shipment" translate="label" type="select" sortOrder="30">
			<label>Can Create Shipment</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
		</field>
		<field id="can_create_creditmemo" translate="label" type="select" sortOrder="40">
			<label>Can Create Credit Memo</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
		</field>
		<field id="can_submit_order_comments" translate="label" type="select" sortOrder="50">
			<label>Can submit comments</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
		</field>
		<field id="hide_customer_email" translate="label" type="select" sortOrder="50">
			<label>Hide Customer Email</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
			<comment>Customer email from order will be hidden.</comment>
		</field>
		<field id="hide_payment_info" translate="label" type="select" sortOrder="50">
			<label>Hide Payment Information</label>
			<source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
			<comment>The payment information of customer will be hidden from order.</comment>
		</field>
	</group>
</advanced_group>
</config>
